-- Connect to your PDB (replace PDBORCL with your actual PDB name if different)
ALTER SESSION
SET
    CONTAINER = PDBORCL;

-- Create user 'myagent' with password 'agent'
CREATE USER myagent IDENTIFIED BY agent;

-- Grant basic privileges
GRANT CONNECT,
RESOURCE TO myagent;

ALTER USER myagent QUOTA UNLIMITED ON USERS;

-- Switch to the new user
ALTER SESSION
SET
    CURRENT_SCHEMA = myagent;

-- Create tables
-- 1️⃣ Product table
CREATE TABLE product (
    product_id VARCHAR2(50) PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(255),
    current_quantity NUMBER(10, 2) NOT NULL,
    threshold_quantity NUMBER(10, 2) NOT NULL
);

-- 2️⃣ Supplier table
CREATE TABLE supplier (
    supplier_id VARCHAR2(50) PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    location VARCHAR2(100),
    pricing_strategy VARCHAR2(50)
);

-- 3️⃣ Catalog table (maps suppliers to products they offer)
CREATE TABLE catalog (
    supplier_id VARCHAR2(50) REFERENCES supplier(supplier_id),
    product_id VARCHAR2(50) REFERENCES product(product_id),
    base_price NUMBER(10, 2) NOT NULL,
    min_order_quantity NUMBER(10) NOT NULL,
    terms VARCHAR2(50),
    PRIMARY KEY (supplier_id, product_id)
);

-- 4️⃣ Stock Alert table
CREATE TABLE stock_alert (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR2(50) REFERENCES product(product_id),
    alert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'PENDING'
);

-- 5️⃣ Supplier Offer table
CREATE TABLE supplier_offer (
    offer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id NUMBER REFERENCES stock_alert(alert_id),
    supplier_id VARCHAR2(50) REFERENCES supplier(supplier_id),
    offered_price NUMBER(10, 2),
    lead_time_days NUMBER(5),
    reliability_score NUMBER(3, 2),
    offer_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'PENDING'
);

-- 6️⃣ Manager Decision table
CREATE TABLE manager_decision (
    decision_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id NUMBER REFERENCES stock_alert(alert_id),
    selected_offer_id NUMBER REFERENCES supplier_offer(offer_id),
    decision_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20)
);

-- Populate initial product data
INSERT INTO
    product (
        product_id,
        name,
        description,
        current_quantity,
        threshold_quantity
    )
VALUES
    (
        'WIDGET_A',
        'Widget Alpha',
        'A top-selling widget',
        200,
        50
    );

INSERT INTO
    product (
        product_id,
        name,
        description,
        current_quantity,
        threshold_quantity
    )
VALUES
    (
        'COMP_B',
        'Component Bravo',
        'High quality component',
        100,
        25
    );

INSERT INTO
    product (
        product_id,
        name,
        description,
        current_quantity,
        threshold_quantity
    )
VALUES
    (
        'MAT_C',
        'Material Charlie',
        'Essential material',
        300,
        100
    );

INSERT INTO
    product (
        product_id,
        name,
        description,
        current_quantity,
        threshold_quantity
    )
VALUES
    ('TOOL_D', 'Tool Delta', 'Durable tool', 50, 20);

-- Populate initial supplier data
INSERT INTO
    supplier (supplier_id, name, location, pricing_strategy)
VALUES
    ('1', 'Supplier Alpha', 'US-East', 'competitive');

INSERT INTO
    supplier (supplier_id, name, location, pricing_strategy)
VALUES
    ('2', 'Supplier Beta', 'EU-West', 'premium');

INSERT INTO
    supplier (supplier_id, name, location, pricing_strategy)
VALUES
    (
        '3',
        'Supplier Gamma',
        'Asia-Pacific',
        'standard'
    );

-- Populate initial catalog data
-- Supplier Alpha
INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('1', 'WIDGET_A', 10.50, 50, 'Net 30');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('1', 'COMP_B', 2.75, 25, 'Net 30');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('1', 'MAT_C', 1.25, 100, 'Net 15');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('1', 'TOOL_D', 45.99, 10, 'COD');

-- Supplier Beta
INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('2', 'WIDGET_A', 11.25, 40, 'Net 30');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('2', 'COMP_B', 2.95, 20, 'Net 30');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('2', 'MAT_C', 1.35, 80, 'Net 15');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('2', 'TOOL_D', 48.50, 5, 'Net 15');

-- Supplier Gamma
INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('3', 'WIDGET_A', 9.75, 60, 'Net 45');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('3', 'COMP_B', 2.50, 30, 'Net 45');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('3', 'MAT_C', 1.15, 120, 'Net 30');

INSERT INTO
    catalog (
        supplier_id,
        product_id,
        base_price,
        min_order_quantity,
        terms
    )
VALUES
    ('3', 'TOOL_D', 42.99, 15, 'Net 30');

COMMIT;